name: Speccy JSON Validation CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: validate JSON URL scheme
      run: |
        docker run wework/speccy lint -v -j https://raw.githubusercontent.com/${{github.repository}}/Master/Release%20Candidate%20Messages/exampleUrlScheme.json

