name: Spectral JSON Validation CI

on: [push]

env:
  REPO_BASE_PATH: https://raw.githubusercontent.com/${{github.repository}}/${GITHUB_REF##*/}
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: validate JSON URL scheme
      run: |
        docker run stoplight/spectral lint {{env.REPO_BASE_PATH}}/url-schemes/exampleUrlScheme.json -r={{env.REPO_BASE_PATH}}/.spectral.yaml -v
        docker run stoplight/spectral lint {{env.REPO_BASE_PATH}}/url-schemes/healthURLScheme.json -r={{env.REPO_BASE_PATH}}/.spectral.yaml -v
